version: '3.4'

services:
  redis:
    container_name: redis-cache
    image: redis
    command: redis-server --requirepass Redis2021!
    ports:
      - "16379:6379"
    networks:
     - identity-jwt

  identityjwt:
    image: ${DOCKER_REGISTRY-}identityjwt
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
     - redis
    networks:
     - identity-jwt

networks:
  identity-jwt: